data_provider:
  rrc_config:
    test_crop_ratio: 0.95
  n_worker: 8
  base_batch_size: 170 #128
  ## Added regularization!
  data_aug:
    name: randaug
    n: 2
    m: 6

net_config:
  name: b1
  dropout: 0
  bb_convattention: True    # my attention
  bb_convin2: True
  grouping: 1
  fastit: True
  bigit: True
  smallv2: True 
  middlev1: True
  middlev2: True
  bighead: True
  model_mult: 1.0


  head_dim_mul: False
  actit: False


run_config:
  n_epochs: 300
  base_lr: 0.000166 # 0.00025 
  bsizemult: 1
  # eval_image_size:
  ## REGULARIZATION
  mixup_config:
    op:
    - - mixup
      - 0.3
      - 1.0
    - - cutmix
      - 0.3
      - 1.0

backbone_drop:
  drop_prob: 0.1
