data_provider:
  rrc_config:
    test_crop_ratio: 0.95
  n_worker: 8
  base_batch_size: 170
  ## Added regularization!
  data_aug:
  - name: randaug
    n: 2
    m: 5 #6
  - name: erase # added
    p: 0.2

net_config:
  name: b1
  dropout: 0
  bb_convattention: True    # my attention
  bb_convin2: True
  grouping: 1
  fastit: True
  bigit: True
  smallv2: True 
  middlev1: True
  bighead: True
  model_mult: 1.0

  
  head_dim_mul: False
  actit: False
  

run_config:
  n_epochs: 300
  base_lr: 0.000125 #0.000166 # 0.000113 (if like L1) # 0.00025 
  bsizemult: 1
  # eval_image_size:
  ## REGULARIZATION
  mixup_config:
    op:
    - - mixup
      - 0.2 #0.3
      - 1.0
    - - cutmix
      - 0.2 #0.3
      - 1.0
    mesa: #added
      thresh: 0.25
      ratio: 2.0

backbone_drop:
  name: droppath
  drop_prob: 0.1
  linear_decay: True #added
  skip: 2 # added